# Generated by Django 3.0.6 on 2020-07-31 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('is_area', models.BooleanField()),
            ],
            options={
                'db_table': 'club',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('ref', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('sex', models.CharField(max_length=1)),
                ('fidecode', models.CharField(max_length=10)),
                ('nation', models.CharField(max_length=3)),
            ],
            options={
                'db_table': 'player',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grading_date', models.DateField()),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('age', models.IntegerField(null=True)),
                ('category', models.CharField(max_length=1)),
                ('grade', models.IntegerField(null=True)),
                ('previous_grade', models.IntegerField(null=True)),
                ('num_games', models.IntegerField()),
                ('rapid_category', models.CharField(max_length=1)),
                ('rapid_grade', models.IntegerField(null=True)),
                ('rapid_previous_grade', models.IntegerField(null=True)),
                ('rapid_num_games', models.IntegerField(null=True)),
                ('club1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grade_club1', to='grades.Club')),
                ('club2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grade_club2', to='grades.Club')),
                ('club3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grade_club3', to='grades.Club')),
                ('club4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grade_club4', to='grades.Club')),
                ('club5', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grade_club5', to='grades.Club')),
                ('club6', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grade_club6', to='grades.Club')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grade_grade', to='grades.Player')),
            ],
            options={
                'db_table': 'grade',
            },
        ),
    ]
