# Generated by Django 3.0.6 on 2020-07-31 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='month',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='year',
        ),
    ]
