# Generated by Django 3.0.6 on 2020-07-31 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0002_auto_20200731_2240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='nation',
        ),
        migrations.AddField(
            model_name='grade',
            name='nation',
            field=models.CharField(default='', max_length=3),
            preserve_default=False,
        ),
    ]
