# Generated by Django 3.0.6 on 2020-08-02 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0004_auto_20200731_2351'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='club',
            unique_together={('name', 'is_area')},
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('ref', 'name', 'sex')},
        ),
    ]
